# Task

* Cài đặt Genetic Algorithm theo bản cài đặt **POPOP** (không sử dụng mutation).

* thực nghiệm bản cài đặt của mình với các **problem size** của hàm OneMax tăng dần như sau: 8, 16, 32, 64, 128

* Ở đầu mỗi lượt chạy, khi khởi tạo quần thể, thì cần đặt lại random seed. Hãy chọn random seed là MSSV của mình.

* Với mỗi problem size, hãy chọn ra population size có khả năng tìm ra được lời giải tối ưu (không chạy quá 50 thế hệ). 

> Bài nộp: 1 file ipynb (Ở cuối file viết một đoạn bình luận ngắn thống kế và nhận xét về kết quả thực nghiệm).

# Code truncation

In [6]:
import numpy as np

In [7]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables ) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [42]:
np.random.seed(42)
pop = initialize_population(8,4)
print(pop)

[[0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 1 1 0]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 0 0]]


In [5]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [6]:
onemax(pop[5,:])

3

In [7]:
def truncation_selection(pop, pop_fitness, selection_size):
    selected_indices = np.argsort(pop_fitness)[-selection_size:]
    return selected_indices

In [8]:
def crossover( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        # Cài đặt phép lai đồng nhất uniform crossover. 
        # Không cần cài đặt đột biến mutation.
        for idx in range(0, num_parameters):
            r = np.random.rand()
            if r < 0.5:
                temp = offspring2[idx] 
                offspring2[idx] = offspring1[idx]
                offspring1[idx] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [9]:
def mutation(pop, mutation_prob):
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    for i in range(0, num_individuals):
        for j in range(0, num_parameters):
            r = np.random.rand()
            if r < mutation_prob:
                if pop[i][j] == 0:
                    pop[i][j] = 1
                else:
                    pop[i][j] = 0
    
    return pop

In [10]:
def genetic_algorithm(num_individuals, num_parameters, num_generations):
    
    # Initialize and evaluate individuals
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = np.array([onemax(ind) for ind in pop])
    print("#Gen 0:")
    print(pop_fitness)

    selection_size = num_individuals // 2

    for i in range(num_generations):
        # Select Parents
        selected_indices = truncation_selection( pop, pop_fitness, selection_size )
        selection_set = pop[selected_indices]
        selection_fitness = pop_fitness[selected_indices]
        
        # Create and evaluate offstring
        offspring = crossover(selection_set)
        offspring = mutation(offspring, 0.1)
        offspring_fitness = np.array([onemax(ind) for ind in offspring])
        
        # P <-- O
        pop = np.vstack([selection_set, offspring])
        pop_fitness = np.concatenate((selection_fitness, offspring_fitness))
        
        # Generation += 1
        print(f'#Gen {i+1}:')
        print(pop_fitness)
    
    print('#Final result:')
    print(pop)
    print(pop_fitness)


In [20]:
num_parameters = 10
num_individuals = 8
num_generations = 10
np.random.seed(19521832)
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[4 6 4 4 7 5 7 5]
#Gen 1:
[5 6 7 7 6 6 5 4]
#Gen 2:
[6 6 7 7 5 8 6 6]
#Gen 3:
[6 7 7 8 7 7 6 3]
#Gen 4:
[7 7 7 8 7 7 6 7]
#Gen 5:
[7 7 7 8 7 7 7 7]
#Gen 6:
[7 7 7 8 6 7 6 6]
#Gen 7:
[7 7 7 8 8 9 6 8]
#Gen 8:
[8 8 8 9 7 9 8 6]
#Gen 9:
[8 8 9 9 6 9 6 8]
#Gen 10:
[8 9 9 9 8 9 8 8]
#Final result:
[[0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 0 1 1 1 1 1]]
[8 9 9 9 8 9 8 8]


# Code POPOP

In [1]:
def tourament_selection(parent_population, popuation_size, tourament_size):
    pass

In [76]:
def convergence(pop):
    n_ind = len(pop)
    print(n_ind)
    
    indice = np.arange(n_ind)
    np.random.shuffle(indice)
    shuffle_pop = np.copy(pop[indice])
    
    all_same = shuffle_pop == pop
    
    return all_same.all()

In [108]:
arr = np.array([[0, 1, 0, 1], [0, 1, 0, 1], [0, 1, 0, 1]])
convergence(arr)

3


True

In [78]:
import numpy as np
 
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
 
comparison = an_array == another_array
print(comparison)
equal_arrays = comparison.all()
 
print(equal_arrays)

[[ True  True]
 [ True  True]]
True


In [2]:
def POPOP_genetic_algorithm():
    # Initialize individuals
    pop = initialize_population(num_individuals, num_variables)
    
    while True:
        
        if convergence(pop) == True: 
            break
    
        # Create offstring
        offstring = crossover(pop)
        # P + O pool
        P_O_pop = np.vstack(pop, offstring)
        # Select parent for next generation
        pop = tournament_selection(P_O_pop, tournament_size, population_size)


SyntaxError: incomplete input (470572905.py, line 1)

## Problem size - 8

In [43]:
num_parameters =  8
num_individuals = 4
np.random.seed(19521832)
POPOP_genetic_algorithm(num_individuals, num_parameters)

NameError: name 'POPOP_genetic_algorithm' is not defined

## Problem size - 16

## Problem size - 32

## Problem size - 64

## Problem size - 128